#!/usr/bin/env python3

from lease_control.session_states import Session
import argparse
import time

# rosrun lease_control create_user  "{'key': [''], 'lesson': '', 'e-mail': ['']}"

parser = argparse.ArgumentParser()
parser.add_argument("--ssh_key", default="", 
                    help="Student ssh key, that will be used for log in")
parser.add_argument("--lesson", default="", 
                    help="The number of lesson")
parser.add_argument("--email", default="", 
                    help="Student email")
args = parser.parse_args()

session_id = time.time()
session = Session(session_id, args.email, key=args.ssh_key, lesson=args.lesson)

session.start_session()
