#!/usr/bin/env python3

from user_control import UserControl
import sys

# rosrun lease_control create_user  "{'key': [''], 'lesson': '', 'e-mail': ['']}"

metadata = sys.argv[1]
uc = UserControl()
passw = uc.create_user_pass()
passw1 = uc.create_user_pass()
user = "student"
uc.add_user_core(user, passw1, metadata)
uc.add_user_spot(user, passw)
uc.estop_pub.publish("press allow")
