#!/usr/bin/env python3

from user_control import UserControl
import sys
import os
import shutil
import time

# rosrun lease_control delete_user.py

user = "student"
uc = UserControl()
uc.delete_user_core(user)
uc.delete_user_spot(user)
uc.estop_pub.publish("press stop")
time.sleep(5)
uc.compress_files(f"/home/spot/{user}/")
ipfs_hash = uc.pin_to_ipfs(f"/home/spot/{user}/")
