#!/usr/bin/env python3

import sys
import os
import shutil
import time
import argparse

from lease_control.session_states import Session

parser = argparse.ArgumentParser()
parser.add_argument("--session_id", default="", 
                    help="ID of required session")
args = parser.parse_args()

session = Session(args.session_id)
while session.state != "finished":
    session.next_state()

