#!/usr/bin/env python3

from user_control import UserControl
import sys
import os
import shutil
import time

# rosrun lease_control delete_user.py

user = "student"
uc = UserControl()
with open('/etc/passwd', 'r') as f:
    for line in f:
        line = line.split(':')
        if line[0] == user:
            info = line[4].split('/')
            mail = info[0]
uc.delete_user_core(user)
uc.delete_user_spot(user)
uc.estop_pub.publish("press stop")
time.sleep(5)
ipfs_hash = uc.pin_to_ipfs(f"/home/spot/{user}/")
shutil.rmtree(f"/home/spot/{user}")
